FROM java:openjdk-8u91-jdk

EXPOSE 8282

ADD bin/wait-for-it.sh /wait-for-it.sh

# FIXME: fix /app volume issue with jdk base image.
RUN mkdir -p /simple-api

ADD simple-api-0.1.war /simple-api/simple-api.war

# CMD /bin/sh -c "java -javaagent:agent/jmx_prometheus_javaagent-0.7-SNAPSHOT.jar=1234:config.yaml -jar /simple-api/simple-api.war --spring.profiles.active=docker"
CMD /bin/sh -c "java -jar /simple-api/simple-api.war --spring.profiles.active=docker"