FROM java:openjdk-8u91-jdk

EXPOSE 8080

ADD bin/wait-for-it.sh /wait-for-it.sh

# FIXME: fix /app volume issue with jdk base image.
RUN mkdir -p /simple-web

ADD simple-web-0.1.war /simple-web/simple-web.war

CMD /bin/sh -c "java -jar /simple-web/simple-web.war --spring.profiles.active=docker"
